fdr<-function(v1,Q){
        #Finding the order of input given
		o1<-order(v1)
		
		#Getting the p-values according to the order of the input
        pvec<-v1[o1]
		
		#Finding the length of the input
        m<-length(v1)
		
		#Getting q-values so that we compare them to p-values(generated by the ttest function) & get significant values from the data
        qline<-Q*c(1:m)/m
		
		#Generating Plot
        plot(c(c(1:m),c(1:m)),c(qline,pvec),type="n",xlab="ordering",ylab="pvalue")
        
		#Plot the q-values(you can see that they are linear and the maximum value attained by them is Q(FDR given by the user))
		lines(c(1:m),qline)
        
		#Plotting the p-values of the input
		points(c(1:m),pvec)
        
		#Finding the difference between p-values and q-values
		dv<-pvec-qline
        
		#Finding the values of input for which the above calculated difference is negative
		I1<-(dv<0)
		
        #Finding the maximum p-value for which the above calculated difference is negative(Also discarding missing p-values)
		pmax<-max(pvec[I1],na.rm=T)
		
		#Finding the input values for which the FALSE DISCOVERY RATE will be Q(given by user) according to BENJAMINI-HOTCHBERG FORMULA
        I2<-pvec<=pmax
		
		#Coloring the sequence red for which the FDR is Q
        points(c(1:m)[I2],pvec[I2],col="red")
		
		#Getting the significant input values in order according to the above method
        o1[I2]

	}